---
- name: Converge

  hosts: localhost

  gather_facts: false

  roles:

    - nephelaiio.plugins

  tasks:

    - name: deploy cluster
      include_role:
        name: nephelaiio.k8s
      vars:
        k8s_deploy: true
        k8s_verify: false
