---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy cluster
      ansible.builtin.include_role:
        name: nephelaiio.k8s
      vars:
        k8s_deploy: true
        k8s_verify: false
