---
- name: Create
  hosts: localhost
  roles:
    - nephelaiio.plugins
  tasks:
    - name: Deploy kind cluster
      when: k8s_molecule_cluster_type == 'kind'
      block:
        - name: Deploy kind cluster
          ansible.builtin.include_role:
            name: nephelaiio.kind
          vars:
            kind_image_tag: "{{ lookup('ansible.builtin.env', 'K8S_RELEASE') | default('v1.24.4') }}"

    - name: Deploy k3s cluster
      when: k8s_molecule_cluster_type == 'k3s'
      block:
        - name: Create k3s tempdir
          ansible.builtin.tempfile:
            state: directory
            prefix: "k3s_"
          register: tempdir

        - name: Retrieve k3s installer
          ansible.builtin.get_url:
            url: https://get.k3s.io
            dest: "{{ tempdir.path }}/k3s"
            mode: 0755

        - name: Deploy k3s cluster
          ansible.builtin.command: "{{ tempdir.path }}/k3s --disable=traefik"
          vars:
            k3s_version: "{{ lookup('ansible.builtin.env', 'K8S_RELEASE') }}+k3s1"
          environment:
            INSTALL_K3S_VERSION: "{{ k3s_version }}"
          become: true

        - name: Install iscsi tools
          ansible.builtin.package:
            name: open-iscsi
          retries: 3
          delay: 10
          register: package_install
          until: package_install is succeeded
          become: yes

        - name: Copy k3s kubeconfig
          ansible.builtin.copy:
            src: "/etc/rancher/k3s/k3s.yaml"
            dest: "{{ k8s_kubeconfig }}"
            remote_src: true
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: 0600
          vars:
            ansible_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
          become: true

        - name: Remove k3s tempdir
          ansible.builtin.file:
            path: "{{ tempdir.path }}"
            state: absent
