---
- name: Destroy
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Destroy kind cluster
      when: k8s_molecule_cluster_type == 'kind'
      block:
        - name: Destroy kind cluster
          ansible.builtin.include_role:
            name: nephelaiio.kind
          vars:
            kind_state: absent
            kind_cluster_state: absent
            kind_image_tag: "{{ lookup('ansible.builtin.env', 'K8S_RELEASE') }}"

    - name: Destroy k3s cluster
      when: k8s_molecule_cluster_type == 'k3s'
      block:
        - name: Stat mysql router state file
          ansible.builtin.stat:
            path: "/usr/local/bin/k3s-uninstall.sh"
          register: k8s_uninstaller

        - name: Destroy k3s cluster
          ansible.builtin.command: "{{ k8s_uninstaller.stat.path }}"
          when: k8s_uninstaller.stat.exists
          become: true

    - name: Delete certificate from edge truststore
      ansible.builtin.command: "certutil -d sql:$HOME/.pki/nssdb -D -n {{ k8s_cluster_name }}"
      changed_when: false
      ignore_errors: true
