---
- name: Destroy Kind cluster
  hosts: localhost
  tasks:
    - name: Destroy Kind cluster
      when: k8s_molecule_cluster_type == 'kind'
      block:
        - name: Destroy Kind cluster
          ansible.builtin.include_role:
            name: nephelaiio.kind
          vars:
            kind_state: absent
            kind_cluster_state: absent
            kind_image_tag: "{{ lookup('ansible.builtin.env', 'K8S_RELEASE') }}"
