---
- name: Verify
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Verify cluster
      ansible.builtin.include_role:
        name: nephelaiio.k8s
      vars:
        k8s_deploy: false
        k8s_verify: true
