---
- name: Update ArgoCD chart
  kubernetes.core.helm:
    name: argocd
    chart_ref: "{{ k8s_argocd_chart.name }}"
    chart_repo_url: "{{ k8s_argocd_chart.repo }}"
    chart_version: "{{ _release }}"
    release_namespace: "{{ k8s_argocd_namespace }}"
    create_namespace: true
    state: present
    wait: true
    wait_timeout: "{{ k8s_argocd_wait_timeout }}s"
    values: "{{ k8s_argocd_chart_values }}"
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    binary_path: "{{ lookup('ansible.builtin.env', 'HELM_BIN', default=k8s_helm_bin) }}"
  vars:
    _release: "{{ k8s_argocd_chart_release | default(k8s_argocd_chart.release) }}"
  listen: argocd_update
