---
- name: Record cert metadata
  ansible.builtin.set_fact:
    cert_failed: "{{ cert_query | community.general.json_query(cert_filter) }}"
  vars:
    cert_filter: "[?status.conditions[?status == 'False' && type == 'Ready']].metadata.name"
    cert_query: "{{
      query(
        'kubernetes.core.k8s',
        kind='Certificate',
        kubeconfig=k8s_kubeconfig
      ) }}"

- name: Validate cert status
  ansible.builtin.fail:
    msg: "the following certificates are in failed status [{{ cert_failed | join(', ') }}]"
  when: cert_failed | length > 0
