---
- name: Query Helm deployments
  ansible.builtin.command: "{{ k8s_helm_bin }} list -A -o json"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig }}"
  register: helm_query
  changed_when: false

- name: Verify reflector deployment
  ansible.builtin.assert:
    that: _helm_reflector | length == 1
    fail_msg: "reflector deployment not found"
  vars:
    _helm_reflector: "{{ helm_query.stdout | from_json | selectattr('name', 'equalto', 'reflector') }}"
