---
- name: Query Helm deployments
  ansible.builtin.command: "{{ k8s_helm_bin }} list -A -o json"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig }}"
  register: helm_query
  changed_when: false

- name: Verify sealedsecrets deployment
  ansible.builtin.assert:
    that: _helm_sealedsecrets | length == 1
    fail_msg: "sealedsecrets deployment not found"
  vars:
    _helm_sealedsecrets: "{{ helm_query.stdout | from_json | selectattr('name', 'equalto', 'sealed-secrets') }}"
