---
- name: Query Helm deployments
  ansible.builtin.command: "{{ k8s_helm_bin }} list -A -o json"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig }}"
  register: helm_query
  changed_when: false

- name: Validate sealed-secrets deployment
  ansible.builtin.assert:
    that: _ss_svc_data | length == 1
    fail_msg: "Could not find service {{ _ss_svc_name }} in namespace {{ k8s_sealedsecrets_namespace }}"
  vars:
    _svc_data: "{{ query(_query, kind='Service', kubeconfig=k8s_kubeconfig) }}"
    _ss_ns_data: "{{ _svc_data | selectattr('metadata.namespace', 'equalto', k8s_sealedsecrets_namespace) }}"
    _ss_svc_name: "{{ k8s_sealedsecrets_values.fullnameOverride }}"
    _ss_svc_data: "{{ _ss_ns_data | selectattr('metadata.name', 'equalto', _ss_svc_name) }}"
  when: "'fullnameOverride' in k8s_sealedsecrets_values"
