---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    k8s_argocd_exec_timeout: 2m
  tasks:
    - name: Mutate and verify cluster
      ansible.builtin.include_role:
        name: nephelaiio.k8s
      vars:
        k8s_deploy: true
        k8s_verify: true
