---
- name: destroy

  hosts: localhost

  gather_facts: false

  vars:

    kind_state: absent
    kind_cluster_state: absent

  roles:

    - nephelaiio.kind

  pre_tasks:

    - name: delete certificate from edge truststore
      ansible.builtin.command: "certutil -d sql:$HOME/.pki/nssdb -D -n {{ k8s_cluster_name }}"
