---
- name: Deploy olm crds
  kubernetes.core.k8s:
    resource_definition: "{{ lookup('url', k8s_olm_manifest_crds, split_lines=False) }}"
    wait: true
    wait_timeout: "{{ k8s_olm_wait_timeout }}"
    wait_condition:
      reason: InitialNamesAccepted
      type: Established
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"

- name: Deploy olm operator
  kubernetes.core.k8s:
    resource_definition: "{{ lookup('url', k8s_olm_manifest_olm, split_lines=False) }}"
    wait: true
    wait_timeout: "{{ k8s_olm_wait_timeout }}"
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
  changed_when: false
