---
- name: Manage SealedSecrets Helm chart
  kubernetes.core.helm:
    name: sealedsecrets
    chart_ref: "{{ k8s_sealedsecrets_chart.name }}"
    chart_repo_url: "{{ k8s_sealedsecrets_chart.repo }}"
    chart_version: "{{ _release }}"
    release_namespace: "{{ k8s_sealedsecrets_namespace }}"
    create_namespace: true
    state: present
    wait: true
    wait_timeout: "{{ k8s_sealedsecrets_wait_timeout }}s"
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    binary_path: "{{ lookup('ansible.builtin.env', 'HELM_BIN', default=k8s_helm_bin) }}"
    values: "{{ k8s_sealedsecrets_values | default(omit) }}"
  vars:
    _release: "{{ k8s_sealedsecrets_chart_release | default(k8s_sealedsecrets_chart.release) }}"
