---
- name: Create cluster secrets
  when: k8s_secrets | length > 0
  block:
    - name: Create cluster namespaces
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop: "{{ k8s_secrets | map(attribute='namespace') }}"

    - name: Create cluster secrets
      kubernetes.core.k8s:
        state: "{{ item.state | default('present') }}"
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata: "{{ item.metadata | default(_defaults_metadata) }}"
          type: "{{ item.type | default('Opaque') }}"
          data: "{{ item.data }}"
      loop: "{{ k8s_secrets }}"
      vars:
        _defaults_metadata: {}
      no_log: true
