---
- block:

    - name: create cluster namespaces
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop: "{{ k8s_secrets | map(attribute='namespace') }}"

    - name: create cluster secrets
      kubernetes.core.k8s:
        state: "{{ item.state | default('present') }}"
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace }}"
          type: "{{ item.type | default('Opaque') }}"
          data: "{{ item.data }}"
      loop: "{{ k8s_secrets }}"
      no_log: true

  when: k8s_secrets | length > 0
