---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: localhost
driver:
  name: default
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    create: ../common/create.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    hosts:
      all:
        vars:
          # test-only vardefs
          ansible_connection: local
          ansible_python_interpreter: python
          gh_token: "{{ lookup('env', 'GH_TOKEN') }}"
          k8s_kubeconfig: "{{ lookup('ansible.builtin.env', 'KUBECONFIG', default='${MOLECULE_EPHEMERAL_DIRECTORY}/config') }}"
          k8s_helm_bin: helm
          k8s_certmanager_issuer_name: local
          k8s_cluster_name: molecule.nephelai.io

          # kind vardefs
          kind_network_addr: 172.19.0.0/16
          kind_bin: ${MOLECULE_EPHEMERAL_DIRECTORY}/kind
          kind_cluster_name: molecule-k8s-${MOLECULE_SCENARIO_NAME}
          kind_kubeconfig: "{{ k8s_kubeconfig }}"
          kind_registry_deploy: false
          kind_proxy_deploy: true
          kind_proxy_cleanup: false
          kind_nodes: 1

          # zalando vardefs
          zalando_user: molecule
          zalando_db: test
          zalando_team: zalando
          zalando_namespace: zalando-test

          # role vardefs
          k8s_address_pool_private_iprange: "{{ kind_network_addr | ansible.utils.ipsubnet(24, 2) }}"
          k8s_metallb_speaker_secret: secret
          k8s_verifier_path: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY', default='${MOLECULE_EPHEMERAL_DIRECTORY}') }}"
          k8s_opensearch_deploy: false
          k8s_strimzi_deploy: false
          k8s_argocd_deploy: false
          k8s_longhorn_deploy: false
          k8s_zalando_deploy: true
          k8s_mysql_deploy: false
          k8s_nginx_deploy: false
          k8s_harbor_deploy: false
          k8s_molecule_cluster_type: k3s
verifier:
  name: ansible
